# Generated by Django 5.2.2 on 2025-06-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_vaga', models.CharField()),
                ('nome_da_empresa', models.CharField()),
                ('data_da_canditatura', models.DateTimeField(auto_now_add=True)),
                ('link_da_vaga', models.CharField()),
                ('houve_resposta', models.BooleanField()),
                ('resposta_final', models.CharField(blank=True, choices=[('nao_selecionado', 'não selecionado'), ('1_fase', '1 fase'), ('2_fase', '2 fase'), ('3_fase', '3 fase'), ('4_fase', '4 fase'), ('5_fase', '5 fase'), ('proposta', 'proposta')], max_length=50, null=True)),
                ('descricao_da_vaga', models.CharField()),
                ('responsavel_pela_vaga', models.CharField()),
                ('detalhes', models.CharField()),
                ('observacoes', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
